name: CD

on:
  workflow_dispatch:

jobs:

  deploy_prod:

    permissions:
      actions: write
      contents: write

    if: github.ref == 'refs/heads/master' # Runs only if the current branch is 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        with:
          name: resume_app
          file: docker-compose-prod.yaml
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          detach: false
          registry_host: ghcr.io
          registry_user: skoval67
          registry_pass: ${{ secrets.GITHUB_TOKEN }}
          summary: true

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
